### ISSUE TITLE
Verify docstring format for all functions

### ISSUE THREAD

**Issue by sputney13** [EricaSkerrett/bme590final#11]

**Comment by sputney13** [comment]
@mlp6  Do functions within a GUI generally have docstrings as well?

**Comment by mlp6** [comment]
Do you have any example one that you can link to?  Some maybe, some not.

**Comment by sputney13** [comment]
https://github.com/EricaSkerrett/bme590final/blob/b85a7ecfd0c3745760efbe8dd603d73c368aa6d9/gui.py#L32

That one, for example, I would assume not.

https://github.com/EricaSkerrett/bme590final/blob/b85a7ecfd0c3745760efbe8dd603d73c368aa6d9/gui.py#L52

Nor would I think so for the ones that initialize buttons, like the link above.

https://github.com/EricaSkerrett/bme590final/blob/b85a7ecfd0c3745760efbe8dd603d73c368aa6d9/gui.py#L67
https://github.com/EricaSkerrett/bme590final/blob/b85a7ecfd0c3745760efbe8dd603d73c368aa6d9/gui.py#L313

For instances like the two above, that determine what the GUI should do after a button is pressed, however, I am less sure.

**Comment by mlp6** [comment]
This is a bit of a gray zone, which is why I asked for some specific examples.  It is not the worst idea for these functions to have a docstring if they are assigned a value to an attribute or otherwise modifying the content of an object.  That being said, many of these are "internal" or "private" functions that aren't going most of the processing, but are really glue for the workflow and would be captured under system testing (not required for this project!).  

Take home recommendation: optional for these.  I've looped in @suyashkumar and @dward2 to make sure that we're on the same page.

**Comment by dward2** [comment]
And, if I can throw my two cents in, primarily from a learning perspective...I'm a fan of documentation so that future developers know what previous developers were doing/thinking (I've personally had to go through thousands of lines of code with virtually no internal documentation, and it was not fun).  So, I lean towards more documentation than less.  But, I'm also a proponent of the idea that the code itself can be its own documentation (e.g., if you have a descriptive variable name, you don't need to have a second comment line documenting what it does).  I think your gui function names and variable names are reasonably descriptive and your functions very modular, so even without any specific comments, it is easy for me to look at a code snippet in your module and know right away what it is doing.  Because of that, I agree that the "internal" functions you cite aren't prime candidates to benefit from docstrings because their function is self-explanatory.
